name: 01 - Building Block

on: push

jobs:
  echo-hello:
    runs-on: self-hosted
    steps:
      - name: Say Hello
        run: echo "Hello Panda"
  echo-buy:
    runs-on: self-hosted
    steps:
      - name: Failed step
        run: |
          echo "failing!"
          exit 1
      - name: Say Buy
        run: echo "Sayoonara"